name: Specification Clarification
description: Request clarification or ask questions about the UAICP specification
title: "[QUESTION] "
labels: ["question", "specification"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for asking a question about the UAICP specification!

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false

  - type: dropdown
    id: section
    attributes:
      label: Which section of the specification?
      multiple: true
      options:
        - Introduction and Design Principles
        - Architecture Overview
        - Universal Discovery Mesh  
        - Protocol Translation Hub
        - Adaptive Router
        - Capability Negotiator
        - Metadata Schema
        - Protocol Integration Guidelines
        - Security Framework
        - Implementation Guidelines
        - Governance and Evolution
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: What is your question?
      description: Please be as specific as possible about what you need clarification on.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: What are you trying to implement or understand? This helps us provide better answers.
      placeholder: I'm trying to implement...
    validations:
      required: false

  - type: textarea
    id: current-understanding
    attributes:
      label: Your current understanding
      description: What do you think the specification means? This helps us identify where clarification is needed.
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/uaicp/uaicp_specification/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true