name: Specification Validation

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  validate-markdown:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install markdownlint
      run: npm install -g markdownlint-cli
      
    - name: Lint Markdown files
      run: markdownlint docs/**/*.md README.md governance/**/*.md tests/**/*.md reference-impl/**/*.md PROJECT-ROADMAP.md

  validate-json:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Validate JSON Schema examples
      run: |
        # Install jq for JSON validation
        sudo apt-get install jq
        
        # Find and validate all JSON examples in the specification
        find docs/ -name "*.md" -exec grep -l '```json' {} \; | while read file; do
          echo "Checking JSON examples in: $file"
          # Extract JSON blocks and validate them (skip if no JSON found)
          if grep -q '```json' "$file"; then
            sed -n '/```json/,/```/p' "$file" | sed '1d;$d' | jq . > /dev/null || echo "Invalid JSON in $file"
          fi
        done

  spell-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install CSpell
      run: npm install -g cspell
        
    - name: Check spelling
      run: cspell "**/*.md" --config .cspell.json

  license-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Check license headers
      run: |
        # Check that all significant files have appropriate license notices
        echo "Checking for license compliance..."
        
        # Check that LICENSE.md exists
        if [ ! -f "LICENSE.md" ]; then
          echo "ERROR: LICENSE.md file is missing"
          exit 1
        fi
        
        echo "License check passed"

  accessibility-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Check documentation accessibility
      run: |
        # Basic accessibility checks for markdown structure
        echo "Checking heading structure..."
        
        # Check for proper heading hierarchy in markdown files
        find docs/ -name "*.md" | while read file; do
          echo "Checking heading structure in: $file"
          # This is a basic check - you might want to use a more sophisticated tool
          grep -n "^#" "$file" | head -5 || echo "No headings found in $file"
        done
