name: Specification Validation

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  validate-markdown:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install markdownlint
      run: npm install -g markdownlint-cli
      
    - name: Lint Markdown files
      run: markdownlint docs/**/*.md README.md
      
    - name: Check for broken links
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
        config-file: '.github/workflows/link-check-config.json'

  validate-json:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Validate JSON Schema examples
      run: |
        # Install jq for JSON validation
        sudo apt-get install jq
        
        # Find and validate all JSON examples in the specification
        find docs/ -name "*.md" -exec grep -l '```json' {} \; | while read file; do
          echo "Checking JSON examples in: $file"
          # Extract JSON blocks and validate them
          sed -n '/```json/,/```/p' "$file" | sed '1d;$d' | jq . > /dev/null || echo "Invalid JSON in $file"
        done

  spell-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Check spelling
      uses: cspell-action/cspell@v1.1.1
      with:
        files: '**/*.md'
        config: '.github/workflows/cspell.json'

  license-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Check license headers
      run: |
        # Check that all significant files have appropriate license notices
        echo "Checking for license compliance..."
        
        # Check that LICENSE.md exists
        if [ ! -f "LICENSE.md" ]; then
          echo "ERROR: LICENSE.md file is missing"
          exit 1
        fi
        
        echo "License check passed"

  accessibility-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Check documentation accessibility
      run: |
        # Basic accessibility checks for markdown structure
        echo "Checking heading structure..."
        
        # Check for proper heading hierarchy in markdown files
        find docs/ -name "*.md" | while read file; do
          echo "Checking heading structure in: $file"
          # This is a basic check - you might want to use a more sophisticated tool
          grep -n "^#" "$file" | head -10
        done